.TH SHELL 1 "December 6, 2023" "Version 1.0" "Simple Shell Manual"

.SH NAME
shell \- Simple Shell

.SH SYNOPSIS
.B shell

.SH DESCRIPTION
\fBshell\fR is a simple shell interpreter for executing Linux commands.

.SH OPTIONS
Once all files are compiled, run:
.PP
\fB$ ./holbertonschool-simple_shell/shell\fR

.SH FILES
\fI/holbertonschool-simple_shell/shell\fR

.SH AUTHORS
The \fBshell\fR program was written by Savanna Davis and Taylor Green.
.PP
GitHub repository: https://github.com/chdrchz/holbertonschool-simple_shell

.SH SEE ALSO
.B sh(1)

.SH BUGS
We know of no bugs.

.SH DATE
December 6, 2023
